name: FlutStuff
version: 1.0
main: de.of.flutstuff.FlutStuff
api-version: 1.26

commands:
  chunkloader:
    description: Hauptbefehl für den Chunkloader
    permission: flutstuff.use
    aliases: [cl]
  cladmin:
    description: Admin-Befehl zum Verwalten aller Chunkloader
    permission: flutstuff.admin
  who:
    description: Zeigt eine Liste aller Spieler und ihrer Discord-Namen
    permission: flutstuff.who
  whoreg:
    description: Verknüpfe deinen Account mit deinem Discord-Namen
    permission: flutstuff.who.register
  cltimeout:
    description: Verhängt ein Timeout über einen Spieler
    permission: flutstuff.admin
    aliases: [timeout]

permissions:
  flutstuff.use:
    description: Darf Chunk-Loader setzen
    default: true
  flutstuff.admin:
    description: Voller Admin-Zugriff (Loader löschen, Config, etc.)
    default: op
    children:
      flutstuff.timeout.give: true   # Admins erben die Permission automatisch
      flutstuff.use: true
      flutstuff.who: true
      flutstuff.timout.immune: true
  flutstuff.who:
    description: Darf /who nutzen
    default: true
  flutstuff.who.register:
    description: Darf /whoreg nutzen
    default: true
  flutstuff.usetimeout:
    description: Darf das eigene Timeout einsehen
    default: true
  flutstuff.timeout.immune:
    description: Kann kein Timeout erhalten
    default: false